data_path: data/gaia-sources-for-npm-colsubset.fits
results_path: results/rv_single_epoch_scatter.v10.pkl
model_path: npm-1d-rv.stan
# Save results every N iterations.
save_interval: 1000000

kdtree_label_names:
 - bp_rp
 - absolute_rp_mag
 - phot_rp_mean_mag
kdtree_minimum_points: 512
kdtree_maximum_points: 512 # randomly sub-sample within the constraints
kdtree_relative_scales: 
 - 0.05
 - 0.50
 - 0.25
kdtree_minimum_radius:
 - 0.1
 - 0.5
 - 0.5
kdtree_maximum_radius:
 - 0.25
 - 2.5
 - 1.5

predictor_label_names:
 - rv_single_epoch_scatter

require_finite_label_names:
 - rv_single_epoch_scatter
 - astrometric_unit_weight_error

share_optimised_result_with_nearest: 0

optimisation_kwds:
  verbose: false
  iter: 10000

parameter_bounds:
  theta: [0, 1]
  mu_single: [0.5, 15]
  sigma_single: [0.05, 10]
  sigma_multiple: [0.2, 5]
  