data_path: data/gaia-sources-for-npm-colsubset.fits
results_path: results/ast.pkl
model_path: npm-1d-rv.stan

kdtree_label_names:
 - bp_rp
 - absolute_g_mag
 - phot_g_mean_mag
kdtree_minimum_points: 512
kdtree_maximum_points: 512 # randomly sub-sample within the constraints
kdtree_relative_scales: 
 - 0.05
 - 0.50
 - 0.25
kdtree_minimum_radius:
 - 0.1
 - 0.5
 - 0.5
kdtree_maximum_radius:
 - 0.25
 - 2.5
 - 1.5

predictor_label_names:
 - astrometric_unit_weight_error

require_finite_label_names:
 - bp_rp
 - rv_single_epoch_scatter
 - astrometric_unit_weight_error
 - absolute_g_mag
 - phot_g_mean_mag
 - absolute_rp_mag
 - phot_rp_mean_mag

number_of_sources: 1000

multiprocessing: true
suppress_stan_output: true

optimisation_kwds:
  verbose: false
  iter: 10000

parameter_bounds:
  theta: [0, 1]
  mu_single: [0.5, 15]
  sigma_single: [0.05, 10]
  sigma_multiple: [0.2, 5]
  