data_path: data/gaia-sources-for-npm-colsubset.fits
results_path: results/astrometric_unit_weight_error.v3.pkl
model_path: npm-1d-rv.stan
# Save results every N iterations.
save_interval: 1000000

kdtree_label_names:
 - bp_rp
 - absolute_rp_mag
 - phot_rp_mean_mag
kdtree_minimum_points: 128
kdtree_maximum_points: 1024 # randomly sub-sample within the constraints
kdtree_relative_scales:
 - 0.1
 - 1.0
 - 1.0
kdtree_minimum_radius:
 - 0.1
 - 0.5
 - 0.5

predictor_label_names:
 #- rv_single_epoch_scatter
 - astrometric_unit_weight_error
 #- phot_bp_rp_excess_factor
 #- rv_abs_diff_template_teff
 #- phot_rp_variability

share_optimised_result_with_nearest: 32

optimisation_kwds:
  verbose: false
  iter: 10000

parameter_bounds:
  theta: [0, 1]
  mu_single: [0.5, 10]
  sigma_single: [0.0, 10]
  sigma_multiple: [0.0, 10]