data_path: data/gaia-sources-for-npm-colsubset.fits
output_data_path: /media/acas0005/muon/velociraptor/npm-output.fits
results_path: results/rv_single_epoch_scatter+no_share.pkl
indices_path: indices.memmap
results_suffix:
model_path: npm-cdf-constraint.stan
overwrite_indices: false

kdtree_label_names:
 - bp_rp
 - absolute_rp_mag
 - phot_rp_mean_mag
kdtree_minimum_points: 128
kdtree_maximum_points: 1024 # randomly sub-sample within the constraints
kdtree_relative_scales:
 - 0.1
 - 1.0
 - 1.0
kdtree_minimum_radius:
 - 0.05
 - 1.0
 - 1.0

predictor_label_names:
 - rv_single_epoch_scatter
 #- astrometric_unit_weight_error
 #- phot_bp_rp_excess_factor
 #- rv_abs_diff_template_teff
 #- phot_rp_variability

share_optimised_result_with_nearest: 0

optimisation_kwds:
  verbose: false
  tol_obj: 1e-15
  tol_grad: 1e-15
  tol_rel_grad: 1e3
  tol_rel_obj: 1e4
  iter: 10000