data_path: data/rv-all-subset-1e4.fits
results_path: results/
results_suffix:
model_path: npm.stan

kdtree_label_names:
 - bp_rp
 - absolute_rp_mag
 - phot_rp_mean_mag
kdtree_minimum_points: 128
kdtree_relative_scales:
 - 0.1
 - 1.0
 - 1.0
kdtree_minimum_radius:
 - 0.05
 - 0.25
 - 0.25

predictor_label_names:
 - rv_single_epoch_scatter
# - astrometric_unit_weight_error
# - phot_bp_rp_excess_factor
# - rv_abs_diff_template_teff
# - phot_rp_variability

#optimisation_strategy: swarm
#initialisation_strategy: swarm
share_optimised_result_with_nearest: 8

optimisation_kwds:
  verbose: false
  tol_obj: 1e-15
  tol_grad: 1e-15
  tol_rel_grad: 1e3
  tol_rel_obj: 1e4
  iter: 10000